import { STRUCTURE_TEMPLATES } from "../templates";
import type { MathCatalogItem } from "./types";

export const MATH_CATALOG: readonly MathCatalogItem[] = [
  {
    id: "fraction",
    kind: "structure",
    category: "structure",
    label: "Phân số",
    latex: STRUCTURE_TEMPLATES.fraction,
    previewLatex: String.raw`\frac{a}{b}`,
    aliases: { vi: ["phân số"], viAscii: ["phan so"], en: ["fraction"], latex: ["frac", "\\frac"] },
  },
  {
    id: "square-root",
    kind: "structure",
    category: "structure",
    label: "Căn thức",
    latex: STRUCTURE_TEMPLATES.squareRoot,
    previewLatex: String.raw`\sqrt{x}`,
    aliases: { vi: ["căn", "căn bậc hai"], viAscii: ["can", "can bac hai"], en: ["root", "square root"], latex: ["sqrt", "\\sqrt"] },
  },
  {
    id: "integral",
    kind: "structure",
    category: "calculus",
    label: "Tích phân",
    latex: STRUCTURE_TEMPLATES.integral,
    previewLatex: String.raw`\int_a^b f(x)\,dx`,
    aliases: { vi: ["tích phân"], viAscii: ["tich phan"], en: ["integral"], latex: ["int", "\\int"] },
  },
  {
    id: "summation",
    kind: "structure",
    category: "calculus",
    label: "Tổng",
    latex: STRUCTURE_TEMPLATES.summation,
    previewLatex: String.raw`\sum_{i=1}^{n} i`,
    aliases: { vi: ["tổng"], viAscii: ["tong"], en: ["sum", "summation"], latex: ["sum", "\\sum"] },
  },
  {
    id: "limit",
    kind: "structure",
    category: "calculus",
    label: "Giới hạn",
    latex: STRUCTURE_TEMPLATES.limit,
    previewLatex: String.raw`\lim_{x\to0} f(x)`,
    aliases: { vi: ["giới hạn"], viAscii: ["gioi han"], en: ["limit"], latex: ["lim", "\\lim"] },
  },
  {
    id: "matrix",
    kind: "structure",
    category: "structure",
    label: "Ma trận",
    latex: STRUCTURE_TEMPLATES.matrix,
    previewLatex: String.raw`\begin{bmatrix}a&b\\c&d\end{bmatrix}`,
    aliases: { vi: ["ma trận"], viAscii: ["ma tran"], en: ["matrix"], latex: ["bmatrix", "matrix"] },
  },
  {
    id: "cases",
    kind: "structure",
    category: "structure",
    label: "Hệ phương trình",
    latex: STRUCTURE_TEMPLATES.cases,
    previewLatex: String.raw`\begin{cases}x&x\ge0\\-x&x<0\end{cases}`,
    aliases: { vi: ["hệ phương trình"], viAscii: ["he phuong trinh"], en: ["cases", "system"], latex: ["cases"] },
  },
  { id: "pi", kind: "symbol", category: "common", label: "Pi", latex: String.raw`\pi`, previewLatex: String.raw`\pi`, aliases: { vi: ["pi"], viAscii: ["pi"], en: ["pi"], latex: ["pi", "\\pi"] } },
  { id: "infinity", kind: "symbol", category: "common", label: "Vô cực", latex: String.raw`\infty`, previewLatex: String.raw`\infty`, aliases: { vi: ["vô cực"], viAscii: ["vo cuc"], en: ["infinity"], latex: ["infty", "\\infty"] } },
  { id: "alpha", kind: "symbol", category: "greek", label: "Alpha", latex: String.raw`\alpha`, previewLatex: String.raw`\alpha`, aliases: { vi: ["alpha"], viAscii: ["alpha"], en: ["alpha"], latex: ["alpha", "\\alpha"] } },
  { id: "beta", kind: "symbol", category: "greek", label: "Beta", latex: String.raw`\beta`, previewLatex: String.raw`\beta`, aliases: { vi: ["beta"], viAscii: ["beta"], en: ["beta"], latex: ["beta", "\\beta"] } },
  { id: "theta", kind: "symbol", category: "greek", label: "Theta", latex: String.raw`\theta`, previewLatex: String.raw`\theta`, aliases: { vi: ["theta"], viAscii: ["theta"], en: ["theta"], latex: ["theta", "\\theta"] } },
  { id: "approximately", kind: "symbol", category: "relation", label: "Xấp xỉ", latex: String.raw`\approx`, previewLatex: String.raw`\approx`, aliases: { vi: ["xấp xỉ"], viAscii: ["xap xi"], en: ["approx"], latex: ["approx", "\\approx"] } },
  { id: "not-equal", kind: "symbol", category: "relation", label: "Không bằng", latex: String.raw`\ne`, previewLatex: String.raw`\ne`, aliases: { vi: ["không bằng"], viAscii: ["khong bang"], en: ["not equal"], latex: ["ne", "\\ne"] } },
  { id: "less-equal", kind: "symbol", category: "relation", label: "Nhỏ hơn hoặc bằng", latex: String.raw`\le`, previewLatex: String.raw`\le`, aliases: { vi: ["nhỏ hơn hoặc bằng"], viAscii: ["nho hon hoac bang"], en: ["less equal"], latex: ["le", "\\le"] } },
  { id: "greater-equal", kind: "symbol", category: "relation", label: "Lớn hơn hoặc bằng", latex: String.raw`\ge`, previewLatex: String.raw`\ge`, aliases: { vi: ["lớn hơn hoặc bằng"], viAscii: ["lon hon hoac bang"], en: ["greater equal"], latex: ["ge", "\\ge"] } },
  { id: "in-set", kind: "symbol", category: "set", label: "Thuộc", latex: String.raw`\in`, previewLatex: String.raw`\in`, aliases: { vi: ["thuộc"], viAscii: ["thuoc"], en: ["element", "in"], latex: ["in", "\\in"] } },
];
