import { STRUCTURE_TEMPLATES } from "../templates";
import type {
  MathCatalogCategory,
  MathCatalogItem,
  MathCatalogKind,
} from "./types";

function entry(
  id: string,
  kind: MathCatalogKind,
  category: MathCatalogCategory,
  label: string,
  latex: string,
  previewLatex: string,
  vi: readonly string[],
  viAscii: readonly string[],
  en: readonly string[],
  latexAliases: readonly string[],
): MathCatalogItem {
  return {
    id,
    kind,
    category,
    label,
    latex,
    previewLatex,
    aliases: { vi, viAscii, en, latex: latexAliases },
  };
}

export const MATH_CATALOG: readonly MathCatalogItem[] = [
  entry("fraction", "structure", "structure", "Phân số", STRUCTURE_TEMPLATES.fraction, String.raw`\frac{a}{b}`, ["phân số"], ["phan so"], ["fraction"], ["frac", "\\frac"]),
  entry("square-root", "structure", "structure", "Căn bậc hai", STRUCTURE_TEMPLATES.squareRoot, String.raw`\sqrt{x}`, ["căn", "căn bậc hai"], ["can", "can bac hai"], ["root", "square root"], ["sqrt", "\\sqrt"]),
  entry("nth-root", "structure", "structure", "Căn bậc n", STRUCTURE_TEMPLATES.nthRoot, String.raw`\sqrt[n]{x}`, ["căn bậc n"], ["can bac n"], ["nth root"], ["sqrt"]),
  entry("superscript", "structure", "structure", "Số mũ", STRUCTURE_TEMPLATES.superscript, String.raw`x^n`, ["số mũ", "lũy thừa"], ["so mu", "luy thua"], ["superscript", "power"], ["^"]),
  entry("subscript", "structure", "structure", "Chỉ số dưới", STRUCTURE_TEMPLATES.subscript, String.raw`x_i`, ["chỉ số dưới"], ["chi so duoi"], ["subscript"], ["_"]),
  entry("matrix", "structure", "structure", "Ma trận 2×2", STRUCTURE_TEMPLATES.matrix, String.raw`\begin{bmatrix}a&b\\c&d\end{bmatrix}`, ["ma trận"], ["ma tran"], ["matrix"], ["bmatrix", "matrix"]),
  entry("determinant", "structure", "structure", "Định thức", STRUCTURE_TEMPLATES.determinant, String.raw`\begin{vmatrix}a&b\\c&d\end{vmatrix}`, ["định thức"], ["dinh thuc"], ["determinant"], ["vmatrix", "det"]),
  entry("cases", "structure", "structure", "Hệ / từng trường hợp", STRUCTURE_TEMPLATES.cases, String.raw`\begin{cases}x&x\ge0\\-x&x<0\end{cases}`, ["hệ phương trình", "từng trường hợp"], ["he phuong trinh", "tung truong hop"], ["cases", "system"], ["cases"]),
  entry("binomial", "structure", "structure", "Tổ hợp", STRUCTURE_TEMPLATES.binomial, String.raw`\binom{n}{k}`, ["tổ hợp", "nhị thức"], ["to hop", "nhi thuc"], ["binomial", "combination"], ["binom"]),
  entry("vector-structure", "structure", "structure", "Vector", STRUCTURE_TEMPLATES.vector, String.raw`\vec{v}`, ["vector", "véc tơ"], ["vector", "vec to"], ["vector"], ["vec"]),
  entry("text", "structure", "structure", "Chữ trong công thức", STRUCTURE_TEMPLATES.text, String.raw`\text{nếu }x>0`, ["chữ", "văn bản"], ["chu", "van ban"], ["text"], ["text"]),

  entry("integral", "structure", "calculus", "Tích phân", STRUCTURE_TEMPLATES.integral, String.raw`\int_a^b f(x)\,dx`, ["tích phân"], ["tich phan"], ["integral"], ["int", "\\int"]),
  entry("summation", "structure", "calculus", "Tổng", STRUCTURE_TEMPLATES.summation, String.raw`\sum_{i=1}^{n}i`, ["tổng"], ["tong"], ["sum", "summation"], ["sum", "\\sum"]),
  entry("product", "structure", "calculus", "Tích", STRUCTURE_TEMPLATES.product, String.raw`\prod_{i=1}^{n}a_i`, ["tích", "tích lớn"], ["tich", "tich lon"], ["product"], ["prod", "\\prod"]),
  entry("limit", "structure", "calculus", "Giới hạn", STRUCTURE_TEMPLATES.limit, String.raw`\lim_{x\to0}f(x)`, ["giới hạn"], ["gioi han"], ["limit"], ["lim", "\\lim"]),
  entry("derivative", "structure", "calculus", "Đạo hàm", STRUCTURE_TEMPLATES.derivative, String.raw`\frac{d}{dx}f(x)`, ["đạo hàm"], ["dao ham"], ["derivative"], ["frac", "d/dx"]),
  entry("partial-derivative", "structure", "calculus", "Đạo hàm riêng", STRUCTURE_TEMPLATES.partialDerivative, String.raw`\frac{\partial f}{\partial x}`, ["đạo hàm riêng"], ["dao ham rieng"], ["partial derivative"], ["partial", "\\partial"]),

  entry("pi", "symbol", "common", "Pi", String.raw`\pi`, String.raw`\pi`, ["pi"], ["pi"], ["pi"], ["pi", "\\pi"]),
  entry("infinity", "symbol", "common", "Vô cực", String.raw`\infty`, String.raw`\infty`, ["vô cực"], ["vo cuc"], ["infinity"], ["infty", "\\infty"]),
  entry("plus-minus", "symbol", "common", "Cộng trừ", String.raw`\pm`, String.raw`\pm`, ["cộng trừ"], ["cong tru"], ["plus minus"], ["pm", "\\pm"]),
  entry("degree", "symbol", "common", "Độ", String.raw`^\circ`, String.raw`90^\circ`, ["độ"], ["do"], ["degree"], ["circ"]),
  entry("ellipsis", "symbol", "common", "Dấu ba chấm", String.raw`\ldots`, String.raw`\ldots`, ["ba chấm"], ["ba cham"], ["ellipsis"], ["ldots", "dots"]),

  entry("alpha", "symbol", "greek", "Alpha", String.raw`\alpha`, String.raw`\alpha`, ["alpha"], ["alpha"], ["alpha"], ["alpha"]),
  entry("beta", "symbol", "greek", "Beta", String.raw`\beta`, String.raw`\beta`, ["beta"], ["beta"], ["beta"], ["beta"]),
  entry("gamma", "symbol", "greek", "Gamma", String.raw`\gamma`, String.raw`\gamma`, ["gamma"], ["gamma"], ["gamma"], ["gamma"]),
  entry("delta", "symbol", "greek", "Delta", String.raw`\delta`, String.raw`\delta`, ["delta"], ["delta"], ["delta"], ["delta"]),
  entry("epsilon", "symbol", "greek", "Epsilon", String.raw`\epsilon`, String.raw`\epsilon`, ["epsilon"], ["epsilon"], ["epsilon"], ["epsilon"]),
  entry("theta", "symbol", "greek", "Theta", String.raw`\theta`, String.raw`\theta`, ["theta"], ["theta"], ["theta"], ["theta"]),
  entry("lambda", "symbol", "greek", "Lambda", String.raw`\lambda`, String.raw`\lambda`, ["lambda"], ["lambda"], ["lambda"], ["lambda"]),
  entry("mu", "symbol", "greek", "Mu", String.raw`\mu`, String.raw`\mu`, ["mu"], ["mu"], ["mu"], ["mu"]),
  entry("rho", "symbol", "greek", "Rho", String.raw`\rho`, String.raw`\rho`, ["rho"], ["rho"], ["rho"], ["rho"]),
  entry("sigma", "symbol", "greek", "Sigma", String.raw`\sigma`, String.raw`\sigma`, ["sigma"], ["sigma"], ["sigma"], ["sigma"]),
  entry("phi", "symbol", "greek", "Phi", String.raw`\phi`, String.raw`\phi`, ["phi"], ["phi"], ["phi"], ["phi"]),
  entry("omega", "symbol", "greek", "Omega", String.raw`\omega`, String.raw`\omega`, ["omega"], ["omega"], ["omega"], ["omega"]),
  entry("Delta", "symbol", "greek", "Delta hoa", String.raw`\Delta`, String.raw`\Delta`, ["delta hoa"], ["delta hoa"], ["capital delta"], ["Delta"]),
  entry("Sigma", "symbol", "greek", "Sigma hoa", String.raw`\Sigma`, String.raw`\Sigma`, ["sigma hoa"], ["sigma hoa"], ["capital sigma"], ["Sigma"]),

  entry("approximately", "symbol", "relation", "Xấp xỉ", String.raw`\approx`, String.raw`\approx`, ["xấp xỉ"], ["xap xi"], ["approximately", "approx"], ["approx"]),
  entry("not-equal", "symbol", "relation", "Không bằng", String.raw`\ne`, String.raw`\ne`, ["không bằng"], ["khong bang"], ["not equal"], ["ne"]),
  entry("less-equal", "symbol", "relation", "Nhỏ hơn hoặc bằng", String.raw`\le`, String.raw`\le`, ["nhỏ hơn hoặc bằng"], ["nho hon hoac bang"], ["less or equal"], ["le"]),
  entry("greater-equal", "symbol", "relation", "Lớn hơn hoặc bằng", String.raw`\ge`, String.raw`\ge`, ["lớn hơn hoặc bằng"], ["lon hon hoac bang"], ["greater or equal"], ["ge"]),
  entry("equivalent", "symbol", "relation", "Tương đương", String.raw`\equiv`, String.raw`\equiv`, ["tương đương"], ["tuong duong"], ["equivalent"], ["equiv"]),
  entry("similar", "symbol", "relation", "Tương tự", String.raw`\sim`, String.raw`\sim`, ["tương tự"], ["tuong tu"], ["similar"], ["sim"]),
  entry("proportional", "symbol", "relation", "Tỷ lệ", String.raw`\propto`, String.raw`\propto`, ["tỷ lệ"], ["ty le"], ["proportional"], ["propto"]),

  entry("in-set", "symbol", "set", "Thuộc", String.raw`\in`, String.raw`\in`, ["thuộc"], ["thuoc"], ["element", "in"], ["in"]),
  entry("not-in-set", "symbol", "set", "Không thuộc", String.raw`\notin`, String.raw`\notin`, ["không thuộc"], ["khong thuoc"], ["not in"], ["notin"]),
  entry("subset", "symbol", "set", "Tập con", String.raw`\subset`, String.raw`\subset`, ["tập con"], ["tap con"], ["subset"], ["subset"]),
  entry("subset-equal", "symbol", "set", "Tập con hoặc bằng", String.raw`\subseteq`, String.raw`\subseteq`, ["tập con hoặc bằng"], ["tap con hoac bang"], ["subset equal"], ["subseteq"]),
  entry("union", "symbol", "set", "Hợp", String.raw`\cup`, String.raw`\cup`, ["hợp"], ["hop"], ["union"], ["cup"]),
  entry("intersection", "symbol", "set", "Giao", String.raw`\cap`, String.raw`\cap`, ["giao"], ["giao"], ["intersection"], ["cap"]),
  entry("empty-set", "symbol", "set", "Tập rỗng", String.raw`\emptyset`, String.raw`\emptyset`, ["tập rỗng"], ["tap rong"], ["empty set"], ["emptyset"]),
  entry("real-numbers", "symbol", "set", "Số thực", String.raw`\mathbb{R}`, String.raw`\mathbb{R}`, ["số thực"], ["so thuc"], ["real numbers"], ["mathbb R"]),
  entry("natural-numbers", "symbol", "set", "Số tự nhiên", String.raw`\mathbb{N}`, String.raw`\mathbb{N}`, ["số tự nhiên"], ["so tu nhien"], ["natural numbers"], ["mathbb N"]),
  entry("integers", "symbol", "set", "Số nguyên", String.raw`\mathbb{Z}`, String.raw`\mathbb{Z}`, ["số nguyên"], ["so nguyen"], ["integers"], ["mathbb Z"]),
  entry("rationals", "symbol", "set", "Số hữu tỉ", String.raw`\mathbb{Q}`, String.raw`\mathbb{Q}`, ["số hữu tỉ"], ["so huu ti"], ["rational numbers"], ["mathbb Q"]),

  entry("times", "symbol", "operator", "Nhân", String.raw`\times`, String.raw`\times`, ["nhân"], ["nhan"], ["times", "multiply"], ["times"]),
  entry("cdot", "symbol", "operator", "Nhân chấm", String.raw`\cdot`, String.raw`\cdot`, ["nhân chấm"], ["nhan cham"], ["dot product", "multiply dot"], ["cdot"]),
  entry("division", "symbol", "operator", "Chia", String.raw`\div`, String.raw`\div`, ["chia"], ["chia"], ["division"], ["div"]),
  entry("nabla", "symbol", "operator", "Nabla", String.raw`\nabla`, String.raw`\nabla`, ["nabla"], ["nabla"], ["nabla", "gradient"], ["nabla"]),
  entry("partial", "symbol", "operator", "Đạo hàm riêng ∂", String.raw`\partial`, String.raw`\partial`, ["đạo hàm riêng"], ["dao ham rieng"], ["partial"], ["partial"]),

  entry("forall", "symbol", "logic", "Với mọi", String.raw`\forall`, String.raw`\forall`, ["với mọi"], ["voi moi"], ["for all"], ["forall"]),
  entry("exists", "symbol", "logic", "Tồn tại", String.raw`\exists`, String.raw`\exists`, ["tồn tại"], ["ton tai"], ["exists"], ["exists"]),
  entry("negation", "symbol", "logic", "Phủ định", String.raw`\neg`, String.raw`\neg`, ["phủ định"], ["phu dinh"], ["not", "negation"], ["neg"]),
  entry("logical-and", "symbol", "logic", "Và", String.raw`\land`, String.raw`\land`, ["và"], ["va"], ["and"], ["land"]),
  entry("logical-or", "symbol", "logic", "Hoặc", String.raw`\lor`, String.raw`\lor`, ["hoặc"], ["hoac"], ["or"], ["lor"]),
  entry("implies", "symbol", "logic", "Suy ra", String.raw`\Rightarrow`, String.raw`\Rightarrow`, ["suy ra"], ["suy ra"], ["implies"], ["Rightarrow"]),
  entry("iff", "symbol", "logic", "Khi và chỉ khi", String.raw`\Leftrightarrow`, String.raw`\Leftrightarrow`, ["khi và chỉ khi"], ["khi va chi khi"], ["if and only if", "iff"], ["Leftrightarrow"]),

  entry("angle", "symbol", "geometry", "Góc", String.raw`\angle`, String.raw`\angle ABC`, ["góc"], ["goc"], ["angle"], ["angle"]),
  entry("perpendicular", "symbol", "geometry", "Vuông góc", String.raw`\perp`, String.raw`a\perp b`, ["vuông góc"], ["vuong goc"], ["perpendicular"], ["perp"]),
  entry("parallel", "symbol", "geometry", "Song song", String.raw`\parallel`, String.raw`a\parallel b`, ["song song"], ["song song"], ["parallel"], ["parallel"]),
  entry("triangle", "symbol", "geometry", "Tam giác", String.raw`\triangle`, String.raw`\triangle ABC`, ["tam giác"], ["tam giac"], ["triangle"], ["triangle"]),

  entry("sin", "symbol", "function", "Sin", String.raw`\sin`, String.raw`\sin x`, ["sin"], ["sin"], ["sine", "sin"], ["sin"]),
  entry("cos", "symbol", "function", "Cos", String.raw`\cos`, String.raw`\cos x`, ["cos"], ["cos"], ["cosine", "cos"], ["cos"]),
  entry("tan", "symbol", "function", "Tan", String.raw`\tan`, String.raw`\tan x`, ["tan"], ["tan"], ["tangent", "tan"], ["tan"]),
  entry("log", "symbol", "function", "Log", String.raw`\log`, String.raw`\log x`, ["log"], ["log"], ["logarithm", "log"], ["log"]),
  entry("ln", "symbol", "function", "Ln", String.raw`\ln`, String.raw`\ln x`, ["ln"], ["ln"], ["natural log", "ln"], ["ln"]),
  entry("exp", "symbol", "function", "Exp", String.raw`\exp`, String.raw`\exp x`, ["hàm mũ"], ["ham mu"], ["exponential", "exp"], ["exp"]),
  entry("min", "symbol", "function", "Min", String.raw`\min`, String.raw`\min(x,y)`, ["nhỏ nhất", "min"], ["nho nhat", "min"], ["minimum", "min"], ["min"]),
  entry("max", "symbol", "function", "Max", String.raw`\max`, String.raw`\max(x,y)`, ["lớn nhất", "max"], ["lon nhat", "max"], ["maximum", "max"], ["max"]),

  entry("hat", "symbol", "accent", "Mũ trên", String.raw`\hat{#0}`, String.raw`\hat{x}`, ["mũ trên"], ["mu tren"], ["hat accent"], ["hat"]),
  entry("bar", "symbol", "accent", "Gạch trên", String.raw`\bar{#0}`, String.raw`\bar{x}`, ["gạch trên"], ["gach tren"], ["bar accent"], ["bar"]),
  entry("vec", "symbol", "accent", "Mũi tên vector", String.raw`\vec{#0}`, String.raw`\vec{v}`, ["mũi tên vector"], ["mui ten vector"], ["vector accent"], ["vec"]),
  entry("dot", "symbol", "accent", "Chấm trên", String.raw`\dot{#0}`, String.raw`\dot{x}`, ["chấm trên"], ["cham tren"], ["dot accent"], ["dot"]),
  entry("ddot", "symbol", "accent", "Hai chấm trên", String.raw`\ddot{#0}`, String.raw`\ddot{x}`, ["hai chấm trên"], ["hai cham tren"], ["double dot"], ["ddot"]),
  entry("overline", "symbol", "accent", "Gạch dài trên", String.raw`\overline{#0}`, String.raw`\overline{AB}`, ["gạch dài trên"], ["gach dai tren"], ["overline"], ["overline"]),
];
